rem .\4_SloPerf.py "PRD MS-AP"
rem .\4_SloPerf.py "PRD MS-LI"
rem .\4_SloPerf.py "PRD MS-PB"
rem .\4_SloPerf.py "PRD MS-RF"
.\4_SloPerf.py "PRD MS-FS"
.\4_SloPerf.py "PRD MS-RP"
.\4_SloPerf.py "PRD MS-PP"
.\4_SloPerf.py "PRD MS-STA"
.\4_SloPerf.py "PRD MS-VW"
.\4_SloPerf.py "PRD MS-CI"
.\4_SloPerf.py "PRD MS-HMP"
.\4_SloPerf.py "PRD MS-SS"
.\4_SloPerf.py "PRD MS-ET"
.\4_SloPerf.py "PRD MS-AS"