rem 5_Slo_MZ_Dashboard.py "PRD MS-AS"
rem 5_Slo_MZ_Dashboard.py "PRD MS-LI"
rem 5_Slo_MZ_Dashboard.py "PRD MS-PB"
rem 5_Slo_MZ_Dashboard.py "PRD MS-RF"
5_Slo_MZ_Dashboard.py "PRD MS-AP"
5_Slo_MZ_Dashboard.py "PRD MS-FS"
5_Slo_MZ_Dashboard.py "PRD MS-RP"
5_Slo_MZ_Dashboard.py "PRD MS-PP"
5_Slo_MZ_Dashboard.py "PRD MS-STA"
5_Slo_MZ_Dashboard.py "PRD MS-VW"
5_Slo_MZ_Dashboard.py "PRD MS-CI"
5_Slo_MZ_Dashboard.py "PRD MS-HMP"
5_Slo_MZ_Dashboard.py "PRD MS-SS"
5_Slo_MZ_Dashboard.py "PRD MS-ET"